nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./cakephp/www/:/var/www/html/
        - ./nginx/nginx.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
    container_name: cakephp_nginx

mysql:
    image: mysql:latest
    volumes:
        - ./mysql/data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: somelongrootpassword
        MYSQL_USER: cakephp
        MYSQL_PASSWORD: cakephp_password
        MYSQL_DATABASE: cakephp
    container_name: cakephp_mysql

php:
    build: ./cakephp
    links:
        - mysql
    volumes:
        - ./cakephp/www/:/var/www/html/
    container_name: cakephp_php
